# Generated by Django 4.0.3 on 2022-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('abstract', models.CharField(max_length=500)),
                ('citations', models.IntegerField()),
            ],
        ),
    ]
